server:
  port: 8081
spring:
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: log
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:sqlite:bot.db
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    hikari:
      minimum-idle: 1
  thymeleaf:
    cache: false

shiro:
  # 注解方式编写的插件无需在插件列表（plugin-list）定义
  # 插件列表为顺序执行，如果前一个插件返回了 MESSAGE_BLOCK 将不会执行后续插件
  plugin-list:
    - com.kuroneko.cqbot.plugin.LogPlugin
    - com.kuroneko.cqbot.plugin.HelpPlugin
    # - com.kuroneko.cqbot.plugin.AiPlugin
    - com.kuroneko.cqbot.plugin.BiLiPlugin
    - com.kuroneko.cqbot.plugin.OvoOaPlugin
    - com.kuroneko.cqbot.plugin.RainbowSixPlugin
    - com.kuroneko.cqbot.plugin.SeTuPlugin
    - com.kuroneko.cqbot.plugin.SubscribePlugin
    - com.kuroneko.cqbot.plugin.TarKovMapPlugin
    - com.kuroneko.cqbot.plugin.ZeroMagnetPlugin
    - com.kuroneko.cqbot.plugin.ThreeHundredPlugin
    - com.kuroneko.cqbot.plugin.RecordPlugin
  # 拦截器
#  interceptor: com.mikuac.example.interceptor.InterceptorExample
  # WebSocket 配置
  ws:
    server:
      enable: true
      # 反向 Websocket 连接地址，无需该配置字段可删除，将使用默认值 "/ws/shiro"
      url: "/ws/cq/"
  # 限速器（令牌桶算法）
  limiter:
    # 是否启用限速器
    enable: false
    # 补充速率（每秒补充的令牌数量）
    rate: 1
    # 令牌桶容量
    capacity: 1
    # 如果该值为 false 时，当令牌获取失败则会直接丢次本次请求
    # 如果该值为 true 时，当令牌获取失败则会阻塞当前线程，后续任务将被添加到等待队列
    awaitTask: true
    # 等待超时
    timeout: 10
  # 线程池配置
  task-pool:
    # 核心线程数（默认线程数）
    core-pool-size: 10
    # 缓冲队列大小
    queue-capacity: 200
    # 允许线程空闲时间（单位：默认为秒）
    keep-alive-time: 10
    # 最大线程数
    max-pool-size: 30
    # 线程池名前缀
    thread-name-prefix: "ShiroTPl-"


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.kuroneko.cqbot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
